"""Department table address column renamed

Revision ID: 0d63be90c7b4
Revises: 1c18c08e2b1c
Create Date: 2024-04-13 12:11:43.750732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63be90c7b4'
down_revision = '1c18c08e2b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name ='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name ='address')

    # ### end Alembic commands ###
