"""Department table renamed

Revision ID: 1c18c08e2b1c
Revises: 2bb5005a71f1
Create Date: 2024-04-13 11:55:24.174378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c18c08e2b1c'
down_revision = '2bb5005a71f1'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
